[package]
name = "mt-ext-authz-grpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
envoy-types = "0.3.0"
tonic = "*"
tokio = { version = "*", features = ["full"] }
anyhow = "1"
